### ISSUE TITLE
[Feedback] Test

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-library-template#56]
### Were you able to successfully create a library with this template? What has been your general experience with this template?

test

### What are the benefits of using this template?

test

### What could be improved with this template?

test

### Have you tried other Processing library templates? If so, which ones?

test

### What was your experience with the other templates?

test

**Comment by vicvalentim** [comment]
Issue: GLSL shaders not accessible in example sketches after migrating from Ant-based library template

Hello,

I recently migrated my Processing library from the previous Ant-based template to the new Gradle-based template. The migration process was mostly smooth, and I didn’t encounter much difficulty re-implementing my library. However, I ran into an issue with GLSL shaders that were working fine in the Ant-based setup but are now inaccessible in the example sketches using the new template.

The shaders (.glsl files) are located in the /library/shaders directory of the library, but when running the examples, they could not be accessed the same way as before. I only managed to get them working by placing the shaders in a /data folder inside /examples/basic.

I would appreciate any help or guidance on how to keep the shaders in the library’s /shaders folder, without the need to move them into the /data folder of each example.

Thank you for your support and assistance!

Best regards,
Victor
