### ISSUE TITLE
Version Number Error: "The version number for 'Library' is not a number" on Installation

### ISSUE THREAD

**Issue by vicvalentim** [processing/processing-library-template#57]
### Describe the bug

When installing the .pdex file compiled using the Gradle template, the Processing console displays the following error message:

"The version number for 'Library' is not a number. Please contact the author to fix it according to the guidelines."

### Steps to reproduce

1 - Compile the library using the Gradle template with version set to 1.1.1.
2 - Install the generated .pdex file in Processing.
3 - Observe the console output when starting Processing or attempting to load the library.

### Expected behavior

The library should install without any version-related error messages in the Processing console.

### Actual behavior

The Processing console shows an error stating that the version number is not recognized as a number. I am currently using version 1.1.1 for my library. Could you provide guidance on the correct way to format version numbers for Processing libraries to prevent this error?

Thank you very much for your assistance!

**Comment by mingness** [comment]
Hello @vicvalentim , 

can you copy here the contents of the txt file in your release artifacts? 

A potential point of confusion is, in the txt file, there are two versions: `prettyVersion` can be a string, while `version` should be an integer. The `version` field in the Gradle build file is mapped to `prettyVersion` in the txt file.  The `version` in the txt file is set by the field `version` in the `release.properties` file. Perhaps the `version` field in the `release.properties` file was also set to "1.1.1"?

If this is the case, then perhaps we should use a different field name in the `release.properties` file. A way to think of the `version` field is, it's the number of versions that have existed for this library. Perhaps `versionIteration`, `versionCount`, or something similar might be more intuitive. Let us know if you an opinion.

**Comment by vicvalentim** [comment]
Hi @mingness, 
This is a release.proprerties from my library,

https://github.com/vicvalentim/ziviDomeLive/blob/main/release.properties

I need help to understand how to effectively define this question about the version, how I will number it.

Now I understand that there is a subtle difference between version and pretty version, what is the methodology then to organize this? is it by revision? 

thank you for your patience with a new processing library developer, 
best regards

**Comment by mingness** [comment]
It's actually very easy, we just aren't explaining it well. You can use `version=1` for your initial release, and any subsequent update, increment the `version`. So for example, the next time you update it, you'll set it as `version=2`. Please keep your `version` in the Gradle file=`prettyVersion` in the txt file ="1.1.1", and increment that as you would like.

Thanks for highlighting this. I'm almost certainly going to change the field name in the `release.properties`.

**Comment by vicvalentim** [comment]
Thanks @mingness, I will adjust this here!
