### ISSUE TITLE
create javadoc output, and verify

### ISSUE THREAD

**Issue by mingness** [processing/processing-library-template#6]
The gradle file currently doesn't create javadocs. 

Tasks:
1. Importing the `java-library` plugin, which adds a javadoc task.
2. verify `build/docs` is as expected

**Comment by enkatsu** [comment]
I will start working on this issue first. Is `/reference` the correct directory for the Javadoc output?

**Comment by mingness** [comment]
Great! The default output for javadocs is in build/docs. The release tasks just need to copy the docs from where they are built into the release folder, and it currently assumes the docs are to be found in build/docs.

**Comment by enkatsu** [comment]
I understand 👌 I'll set up the javadoc task to output to the default directory.

**Comment by mingness** [comment]
Hi @enkatsu , I feel very embarassed. I should have updated the issue with more information.
So, the java-library plugin will actually create a javadoc task. So, I added the plugin as part of the the last PR, because the plugin adds some convenient configurations, like the compileOnly configuration, which I used for the Processing dependency. so, the repo already had a javadoc task. I just wasn't sure if the output was correct / fit for the job.
So, I guess the first task for the issue was check if the javadoc task built into the java-library plugin worked well already.

**Comment by enkatsu** [comment]
Hi @mingness , I'm sorry for jumping to conclusions. Thank you for the detailed explanation 🙏  I understand now that I should have checked whether the existing javadoc task works correctly for the Processing library. I've only done some basic tests so far, so I will test it thoroughly and report back on how it works.

**Comment by enkatsu** [comment]
Hello @mingness , I conducted two tests regarding JavaDoc generation with `./gradlew javadoc`. The first test was creating a class within the `com.example` package to see if it would be reflected in the JavaDoc. The second test involved using a dependent third-party library to check if the documentation would be generated correctly. Both tests seemed to generate the appropriate documentation, so please check the screenshots.

Does this approach look good to you? Also, if there are any other test items that should be checked, I would appreciate your advice 🙏 

![Screenshot 2024-07-30 at 23-17-53 HelloLibrary (HelloLibrary 1 0-SNAPSHOT API)](https://github.com/user-attachments/assets/1ff78907-4482-4e95-94ec-d5b6ed495723)
![Screenshot 2024-07-30 at 23-18-09 TestClass (HelloLibrary 1 0-SNAPSHOT API)](https://github.com/user-attachments/assets/b8bc999e-018f-4b3f-8d54-3d9a06ffdb8a)
![Screenshot 2024-07-30 at 23-18-19 com example (HelloLibrary 1 0-SNAPSHOT API)](https://github.com/user-attachments/assets/12270f05-4c34-480e-bdae-ea1f0487d327)

**Comment by mingness** [comment]
Thanks, that looks good to me :pray: I would say job done.
