### ISSUE TITLE
Add GitHub Actions workflow for distribute libraries

### ISSUE THREAD

**Issue by enkatsu** [processing/processing-library-template#9]
How about adding a workflow like [this](https://github.com/enkatsu/processing-library-template-gradle/blob/main/.github/workflows/release.yml) after resolving [this issue](https://github.com/mingness/processing-library-template/issues/5)? With this workflow, library developers would find it easier to distribute libraries.

**Comment by mingness** [comment]
A GitHub action workflow for releasing is a great idea. 

Here is also a GitHub tutorial on the topic 
https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions

**Comment by SableRaf** [comment]
Fixed in https://github.com/mingness/processing-library-template/pull/20
